name: Publish Docker image

on:
  push:
    branches:
    - main

jobs:
  push_to_registries:
    name: Push Docker image 
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: inspirehep/cronjob-controller:${{ github.sha }}
          cache-from: type=registry,ref=inspirehep/cronjob-controller:buildcache
          cache-to: type=registry,ref=inspirehep/cronjob-controller:buildcache:mode=max
